# Generated by Django 5.2.12 on 2026-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('buyer', 'Buyer'), ('vendor', 'Vendor'), ('admin', 'Admin'), ('delivery_partner', 'Delivery Partner')], default='buyer', max_length=20),
        ),
    ]
