# Generated by Django 5.2.12 on 2026-06-07 17:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0013_order_gst_on_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=30, unique=True)),
                ('invoice_type', models.CharField(choices=[('SELLER_TO_BUYER', 'Seller to Buyer'), ('PLATFORM_TO_BUYER', 'Platform to Buyer'), ('PLATFORM_TO_SELLER_COMMISSION', 'Commission Invoice'), ('BUYER_COMBINED_WRAPPER', 'Combined Buyer Invoice'), ('SETTLEMENT_STATEMENT', 'Settlement Statement'), ('TCS_MONTHLY_STATEMENT', 'TCS Statement'), ('CREDIT_NOTE', 'Credit Note')], max_length=40)),
                ('issuer_name', models.CharField(max_length=200)),
                ('issuer_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('issuer_state', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_gstin', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_state', models.CharField(blank=True, max_length=100, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('is_interstate', models.BooleanField(default=False)),
                ('taxable_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=10)),
                ('pdf_url', models.TextField(blank=True, null=True)),
                ('fy', models.CharField(default='2526', max_length=4)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='orders.order')),
                ('original_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='invoices.invoice')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.IntegerField()),
                ('description', models.TextField()),
                ('hsn_or_sac', models.CharField(blank=True, max_length=8, null=True)),
                ('qty', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('unit', models.CharField(default='nos', max_length=8)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taxable_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('gst_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sgst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='invoices.invoice')),
            ],
            options={
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20)),
                ('fy', models.CharField(max_length=4)),
                ('last_no', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('series', 'fy')},
            },
        ),
    ]
