# Generated by Django 5.2.12 on 2026-05-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0018_product_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
