# Generated by Django 5.2.12 on 2026-05-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0019_vendor_bank_account_name_vendor_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('supermarket', 'Supermarket'), ('bakery', 'Bakery'), ('veg_fruits', 'Veg & Fruits')], max_length=20),
        ),
    ]
