# Generated by Django 5.2.12 on 2026-06-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0021_update_vendor_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('food_meals', 'Food & Meals'), ('grocery_staples', 'Grocery & Staples'), ('bakery_sweets', 'Bakery & Sweets'), ('fresh_produce', 'Fresh Produce'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy'), ('bakery', 'Bakery'), ('snacks', 'Snacks'), ('beverages', 'Beverages'), ('food', 'Food'), ('grocery', 'Grocery'), ('restaurant', 'Restaurant'), ('supermarket', 'Supermarket'), ('fast_food', 'Fast Food'), ('chinese', 'Chinese'), ('ice_cream', 'Ice Cream'), ('fresh_leafies', 'Fresh Leafies'), ('fresh_veggies', 'Fresh Veggies'), ('staples', 'Staples'), ('dal_pulses', 'Dal & Pulses'), ('oils', 'Oils'), ('spices', 'Spices'), ('masala_powders', 'Masala Powders'), ('sugar_salt', 'Sugar & Salt'), ('dry_fruits', 'Dry Fruits'), ('milk', 'Milk'), ('curd', 'Curd'), ('butter', 'Butter'), ('paneer', 'Paneer'), ('ghee', 'Ghee'), ('eggs', 'Eggs'), ('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('main_course', 'Main Course'), ('biryani', 'Biryani'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
