# Generated by Django 5.2.12 on 2026-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0022_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='state',
            field=models.CharField(default='Andhra Pradesh', max_length=100),
        ),
    ]
