# Generated by Django 5.2.12 on 2026-06-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0023_vendor_gstin_vendor_pan_vendor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='min_order',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
