# Generated by Django 5.2.12 on 2026-06-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0024_vendor_min_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='fssai_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
