# Generated by Django 5.2.12 on 2026-06-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0025_vendor_fssai_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='fssai_certificate',
            field=models.ImageField(blank=True, null=True, upload_to='fssai_certificates/'),
        ),
    ]
