# Generated by Django 5.2.12 on 2026-07-10 00:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0027_product_allergen_info_product_barcode_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
