# Generated by Django 5.2.12 on 2026-08-06 12:38

import cloudinary.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_type', models.CharField(blank=True, choices=[('bike', 'Bike'), ('scooter', 'Scooter'), ('bicycle', 'Bicycle')], max_length=10, null=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhaar_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('driving_licence_number', models.CharField(blank=True, max_length=20, null=True)),
                ('driving_licence_document', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('selfie_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('pending_kyc', 'Pending KYC'), ('pending_verification', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_kyc', max_length=25)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_partner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Partner Profile',
                'verbose_name_plural': 'Delivery Partner Profiles',
                'db_table': 'delivery_partner_profiles',
            },
        ),
    ]
