# Generated by Django 5.2.12 on 2026-08-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypartner',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverypartner',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
