# Generated by Django 5.2.12 on 2026-05-22 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cart_unique_together_cart_price_cart_variant_and_more'),
        ('vendors', '0018_product_is_veg'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendors.productvariant'),
        ),
    ]
