# Generated by Django 5.2.12 on 2026-06-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_returnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_on_delivery',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
