# Generated by Django 5.2.12 on 2026-07-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_refund'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refund',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='refund_photos/'),
        ),
    ]
