# Generated by Django 5.2.12 on 2026-08-13 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_photo_comment_to_refund'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='dp_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('offered', 'Offered'), ('accepted', 'Accepted'), ('arrived_at_shop', 'Arrived at Shop'), ('picked_up', 'Picked Up'), ('arrived_at_buyer', 'Arrived at Buyer'), ('delivered', 'Delivered')], default='unassigned', max_length=20),
        ),
    ]
